%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Quantitative Asset And Risk Management 
% Asset Project - Trend Following (Baltas 2015) 
%
% Benjamin Souane, Antoine-Michel Alexeev, Ludovic Suchet and Julien Bisch
% Due Date: April 2020
%==========================================================================

%% Goal of the code

% This code aims to replicate the paper by Baltas 2015.

%   The concept is to implement a trend following strategy with a risk
%   parity weighting scheme. 

%       There is 3 main part to the code: 

%       1. Testing the Auto-Correlation of the data.
%       2. Implementing the stratety with a volatilty parity weighting
%       scheme (naive parity).
%       3. Implementing the strategy with a risk parity weighting scheme.

%% How to use the code 

% There is one main code named "Main.m", it calls all the ohter functions
% and script. Then the output is stored in the Output Folders. 

% To run it, you just need to change your path in the line 13 and 16 of
% "Main.m" to add the functions generated by the group and Kevin Shepperd
% toolBox. 

%% Detailed implementation of the code

% VOLATILITY PARITY

% 1. Compute the Weights through the VolParity Function
% 2. Compute the Signal through the SignalComputing Function
% 3. Compute the leverage and the Portfolio Volatility through the Leverage
% function
% 4. Compute the Return of the stratey through the ReturnStrategy Function
% 5. Compute the Marginal Contribution to risk through the MCR Function

% RISK PARITY

% 1. Compute the Weights through the RiskParityOpti Function using the
% Weights of the volatility parity scheme as initial points
% 2. Compute the Return of the strategy through the ReturnStrategyRiskPar
% function 
% 3. Compute the Marginal Contribution to risk through the MCR Function
